name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: macos-11
    steps:
      - name: Run build
        run: .github/workflows/build-hadoop.sh
