name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Run build
        run: .github/workflows/build-hadoop.sh
