name: Build

on:
  pull_request:
  push:
    branches:
      - main

env:
  PROTOBUF_VERSION: 3.7.1
  HADOOP_VERSION: 3.3.4

jobs:
  build:
    name: Build and Test
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      # Tweak the official cache action to allow save on failure
      - name: Checkout actions/cache@v3
        uses: actions/checkout@v3
        with:
          repository: actions/cache
          ref: v3
          path: .tmp/actions/cache
      - name: Make actions/cache@v3 run always, not only when job succeeds
        # Tweak `action.yml` of `actions/cache@v3` to remove its `post-if`
        # condition, making it default to `post-if: always()`.
        run: |
          sed -i -e '/ post-if: /d' .tmp/actions/cache/action.yml
      - name: Install deps
        run: .github/workflows/install-deps.sh
      - name: Load protobuf from cache
        id: protobuf-cache
        uses: ./.tmp/actions/cache
        with:
          path: protobuf
          key: protobuf-${{env.PROTOBUF_VERSION}}
      - name: Run build protobuf
        if: steps.protobuf-cache.outputs.cache-hit != 'true'
        run: .github/workflows/build-protobuf.sh
      - name: Run install protobuf
        run: .github/workflows/install-protobuf.sh
      - name: Run build hadoop
        run: .github/workflows/build-hadoop.sh
      - name: Save native libs
        uses: actions/upload-artifact@v3
        with:
          name: native
          path: /opt/hadoop-$HADOOP_VERSION/lib/native/*